extends GutTest

var MYPLANTS = preload("res://scenes/my_plant.tscn")
var MYPLANTLOW = preload("res://scenes/low_light_plant.tscn")
var SPAWNSEED = preload("res://scenes/drag_seed.tscn")

func test_myPlant_high():
	var thisArea = SPAWNSEED.instantiate()
	var potatoePlant = MYPLANTS.instantiate()
	var wheatPlant = MYPLANTS.instantiate()
	var tomatoePlant = MYPLANTS.instantiate()
	add_child_autofree(thisArea)
	add_child_autofree(potatoePlant)
	add_child_autofree(wheatPlant)
	add_child_autofree(tomatoePlant)
	thisArea = thisArea.get_child(0)
	potatoePlant.setGlobalVariables(true, 2, 4)
	potatoePlant._on_plant_collision_area_entered(thisArea)
	assert_eq(potatoePlant.spriteAnim.animation, "growPotatoes")
	wheatPlant.setGlobalVariables(true, 2, 5)
	wheatPlant._on_plant_collision_area_entered(thisArea)
	assert_eq(wheatPlant.spriteAnim.animation, "growWheats")
	tomatoePlant.setGlobalVariables(true, 2, 6)
	tomatoePlant._on_plant_collision_area_entered(thisArea)
	assert_eq(tomatoePlant.spriteAnim.animation, "growTomatoes")
	
func test_myPlant_low():
	var thisArea = SPAWNSEED.instantiate()
	var lettacePlant = MYPLANTLOW.instantiate()
	var radishPlant = MYPLANTLOW.instantiate()
	var chivesPlant = MYPLANTLOW.instantiate()
	add_child_autofree(thisArea)
	add_child_autofree(lettacePlant)
	add_child_autofree(radishPlant)
	add_child_autofree(chivesPlant)
	thisArea = thisArea.get_child(0)
	lettacePlant.setGlobalVariables(true, 1, 1)
	lettacePlant._on_low_plant_coll_area_entered(thisArea)
	assert_eq(lettacePlant.spriteAnim.animation, "lettaceGrow")
	radishPlant.setGlobalVariables(true, 1, 2)
	radishPlant._on_low_plant_coll_area_entered(thisArea)
	assert_eq(radishPlant.spriteAnim.animation, "radishGrow")
	chivesPlant.setGlobalVariables(true, 1, 3)
	chivesPlant._on_low_plant_coll_area_entered(thisArea)
	assert_eq(chivesPlant.spriteAnim.animation, "chivesGrow")

func test_high_trowel():
	var thisArea = SPAWNSEED.instantiate()
	var testPlant = MYPLANTS.instantiate()
	add_child_autofree(thisArea)
	add_child_autofree(testPlant)
	testPlant.setGlobalVariables(false, 1, 3)
	testPlant.setPlantGrowing(true)
	testPlant._on_plant_collision_area_entered(thisArea)
	assert_false(testPlant.isPlantGrowing())
	assert_eq(Global.seedSelected, 0)
	assert_eq(testPlant.spriteAnim.animation, "none")
	
func test_low_trowel():
	var thisArea = SPAWNSEED.instantiate()
	var testPlant = MYPLANTLOW.instantiate()
	add_child_autofree(thisArea)
	add_child_autofree(testPlant)
	testPlant.setGlobalVariables(false, 2, 4)
	testPlant.setPlantGrowing(true)
	testPlant._on_low_plant_coll_area_entered(thisArea)
	assert_false(testPlant.isPlantGrowing())
	assert_eq(Global.seedSelected, 0)
	assert_eq(testPlant.spriteAnim.animation, "none")
	
